# Generated by Django 5.1.1 on 2024-10-21 14:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_alter_moodentry_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="moodentry",
            name="rating",
            field=models.IntegerField(default=0),
        ),
    ]
